{
 "title": "Host Status",
 "description": "Up/down status of Raspberry Pis from Prometheus.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Raspberry Pi status from Prometheus",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "max_over_time(up[45s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Attached unassigned temp sensors - shed",
   "type": "logs",
   "description": "Temperature sensors that are attached to the Raspberry Pi but not found in the json config file, effectively unassigned.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"SandstoneRasPi4b8GbPowerMonitor\", service=\"getTemps\"} |= \"Attached unassigned:\"\n| regexp \"Attached unassigned: (?P<sensor_id>.+)\"\n| line_format \"{{.sensor_id}}\"",
     "maxLines": 1000
    },
    {
     "direction": "backward",
     "expr": "{host=\"SandstoneRasPi4b8GbPowerMonitor\", service=\"getTemps\"} |= \"Attached unassigned sensors\"\n| regexp \"Attached unassigned sensors: (?P<count>.+)\"\n| line_format \"Attached unassigned sensors: {{.count}}\""
    }
   ]
  },
  {
   "title": "Assigned unattached temp sensors - shed",
   "type": "logs",
   "description": "Temperature sensors that are found in the json config file but not attached to the Raspberry Pi.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"SandstoneRasPi4b8GbPowerMonitor\", service=\"getTemps\"} |= \"Assigned unattached:\"\n| regexp \"Assigned unattached: (?P<sensor_id>.+)\"\n| line_format \"{{.sensor_id}}\""
    },
    {
     "direction": "backward",
     "expr": "{host=\"SandstoneRasPi4b8GbPowerMonitor\", service=\"getTemps\"} |= \"Assigned unattached sensors\"\n| regexp \"Assigned unattached sensors: (?P<count>.+)\"\n| line_format \"Assigned unattached sensors: {{.count}}\""
    }
   ]
  }
 ]
}