{
 "title": "System Metrics - Shed",
 "description": "System metrics for 192.168.30.5",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage % (avg all cores)",
   "type": "timeseries",
   "description": "Total CPU time spent, labeled by mode (user, system, idle, iowait, etc.) and cpu number",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"shed\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "(\n    rate(node_network_receive_bytes_total{job=\"shed\", device!=\"lo\"}[5m]) +\n    rate(node_network_transmit_bytes_total{job=\"shed\", device!=\"lo\"}[5m])\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - (rate(node_cpu_seconds_total{mode=\"idle\", job=\"shed\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"shed\"} - node_memory_MemAvailable_bytes{job=\"shed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"shed\", device!=\"loop\"}[5m]) +\nrate(node_disk_written_bytes_total{job=\"shed\", device!=\"loop\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load avg 1 min",
   "type": "timeseries",
   "description": "The system load average over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_load1{job=\"shed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{job=\"shed\", fstype!=\"tmpfs\",fstype!=\"overlay\"} \n            / node_filesystem_size_bytes{job=\"shed\", fstype!=\"tmpfs\",fstype!=\"overlay\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load avg  5 min",
   "type": "timeseries",
   "description": "System load average over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_load5{job=\"shed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System temperature",
   "type": "timeseries",
   "description": "Temperature in millidegrees Celsius (per thermal zone)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"shed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load avg 15 min",
   "type": "timeseries",
   "description": "System load average over the last 15 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "node_load15{job=\"shed\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}