{
 "title": "Dashboard - Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CurrentCondition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT last(*) FROM \"autogen\".\"weather\"\n",
     "select": [
      [
       { "params": [ "currentCondition" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "type": "library-panel-ref", "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 } },
  { "title": "Shed and Booty Wall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Shed Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Shed Inside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temps",
     "query": "SELECT last(\"humidity\") FROM \"autogen\".\"temps\" WHERE (\"location\"::tag = 'shedSHT30')",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "shedSHT30" }
     ]
    }
   ]
  },
  {
   "title": "Manifold Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Shed Manifold Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressures",
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'manifold')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "manifold" }
     ]
    }
   ]
  },
  {
   "title": "Booty Wall Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Booty Wall Enclosure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Booty Wall Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Booty Wall Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'bootyWall')"
    }
   ]
  },
  { "title": "Stage Wall and Derrick Wall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Stage Wall Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Stage Wall Enclosure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Stage Wall Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Stage Wall Box",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Derrick Wall Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Derrick Wall Enclosure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Derrick Wall Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Derrick Wall Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'derrickWall')"
    }
   ]
  },
  { "title": "School Room Areas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "School Room Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "School Room Enclosure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "School Rm Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "School Room Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'schoolRoomDump')"
    }
   ]
  },
  {
   "title": "Upper Schl Rm Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Upper Schl Rm Encl",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Upper Schl Rm Water",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Upper Schl Rm Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'upperSchoolRoom')"
    }
   ]
  },
  { "title": "North End and Main Flow Area", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "North End Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "North End Enclosure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "North End Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "North End Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'northEnd')"
    }
   ]
  },
  {
   "title": "Main Flow Outside",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Main Flow Enclosure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Main Flow Water Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 53 }
   ]
  },
  {
   "title": "Main Flow Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"autogen\".\"pressures\" WHERE (\"location\"::tag = 'mainFlow')"
    }
   ]
  },
  { "title": "Power Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '1') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '2') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '3') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '4') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"home_load\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '3') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"power\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '4') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"current\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '1') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"current\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '2') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"current\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '3') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"current\") FROM \"autogen\".\"raw_cts\" WHERE (\"ct\"::tag = '4') AND $timeFilter GROUP BY time(5s) fill(previous)"
    }
   ]
  },
  { "title": "All Temps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Current Temps",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "SELECT last(\"temp_flt\") FROM \"autogen\".\"temps\" WHERE $timeFilter GROUP BY \"title\"::tag, \"id\"::tag, \"location\"::tag, \"type\"::tag, \"hostname\"::tag, \"status\"::tag"
    }
   ]
  }
 ]
}