- name: Import copy_common_functions
  ansible.builtin.import_tasks: ../roles/common/tasks/copy_common_functions.yaml

- name: Copy getWeather.py to the app dir
  ansible.builtin.copy:
    src: "../../src/getWeather.py"
    dest: "{{ app_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  notify: Restart getWeather.service
  tags: app_files

- name: Deploy systemd getWeather.service
  ansible.builtin.copy:
    src: "../systemd/getWeather.service"
    dest: "/etc/systemd/system/getWeather.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd daemon
    - Restart getWeather.service
  become: true
  tags: systemd

- name: Deploy logrotate config file
  ansible.builtin.copy:
    src: "../logrotate/getWeather"
    dest: "/etc/logrotate.d"
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: logging
