---
log_dir: "/var/log/SandstoneDashboard"
app_dir: "/home/{{ ansible_user }}/SandstoneDashboard"
config_dir: "{{ app_dir }}/config"
venv_path: "{{ app_dir }}/venv"
requirements_file: "{{ app_dir }}/requirements.txt"
